<?php

namespace BaseBundle\Repository;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function dateCompare($p,$l){
        $q=$this->getEntityManager()
            ->createQuery("select m.time from BaseBundle:Appointment m 
              WHERE m.date=:p AND m.vetid=:l ")
            ->setParameter('p',$p)->setParameter('l',$l);
        return $q->getResult();
    }
    public function aptUser($l){
        $q=$this->getEntityManager()
            ->createQuery("select m from BaseBundle:Appointment m 
              WHERE m.userId=:l AND m.date>CURRENT_DATE() ")
            ->setParameter('l',$l);
        return $q->getResult();
    }

}
