<?php

namespace BaseBundle\Repository;

/**
 * DreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreRepository extends \Doctrine\ORM\EntityRepository
{
}
